# Generated by Django 2.1.5 on 2019-10-22 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.TextField(blank=True, default=None, null=True)),
                ('price_inr', models.IntegerField(blank=True, default=None, null=True)),
                ('price_usd', models.IntegerField(blank=True, default=None, null=True)),
                ('link_inr', models.SlugField(blank=True, default=None, null=True)),
                ('link_usd', models.SlugField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreateAdmissionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.TextField(blank=True, default=None, null=True)),
                ('price_inr', models.IntegerField(blank=True, default=None, null=True)),
                ('price_usd', models.IntegerField(blank=True, default=None, null=True)),
                ('link_inr', models.SlugField(blank=True, default=None, null=True)),
                ('link_usd', models.SlugField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FreeConsultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(blank=True, default=None, null=True)),
                ('service', models.TextField(blank=True, default=None, null=True)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GreConsultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.TextField(blank=True, default=None, null=True)),
                ('price_inr', models.IntegerField(blank=True, default=None, null=True)),
                ('price_usd', models.IntegerField(blank=True, default=None, null=True)),
                ('link_inr', models.SlugField(blank=True, default=None, null=True)),
                ('link_usd', models.SlugField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.TextField(blank=True, default=None, null=True)),
                ('price_inr', models.IntegerField(blank=True, default=None, null=True)),
                ('price_usd', models.IntegerField(blank=True, default=None, null=True)),
                ('link_inr', models.SlugField(blank=True, default=None, null=True)),
                ('link_usd', models.SlugField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KaplanAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.TextField(blank=True, default=None, null=True)),
                ('password', models.TextField(blank=True, default=None, null=True)),
                ('sold', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('sold_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LORPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customizations', models.IntegerField(blank=True, default=None, null=True)),
                ('price_usd', models.IntegerField(blank=True, default=None, null=True)),
                ('price_inr', models.IntegerField(blank=True, default=None, null=True)),
                ('link_inr', models.SlugField(blank=True, default=None, null=True)),
                ('link_usd', models.SlugField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.TextField(blank=True, default=None, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('pending', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaidMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default=None, null=True)),
                ('details', models.TextField(blank=True, default=None, null=True)),
                ('price_inr', models.IntegerField(blank=True, default=None, null=True)),
                ('price_usd', models.IntegerField(blank=True, default=None, null=True)),
                ('purchase_times', models.IntegerField(blank=True, default=None, null=True)),
                ('limited', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(blank=True, default=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, default=None, null=True, upload_to='paid_material/')),
                ('price_about_to_increase', models.BooleanField(default=False)),
                ('slug', models.SlugField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.TextField(blank=True, default=None, null=True)),
                ('service_name', models.TextField(blank=True, null=True, verbose_name=services.models.Service)),
                ('status', models.TextField(blank=True, default=None, null=True)),
                ('currency', models.TextField(default='INR')),
                ('amount', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrincetonAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.TextField(blank=True, default=None, null=True)),
                ('password', models.TextField(blank=True, default=None, null=True)),
                ('sold', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('sold_to', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrincetonGMATAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.TextField(blank=True, default=None, null=True)),
                ('password', models.TextField(blank=True, default=None, null=True)),
                ('sold', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('sold_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.TextField(blank=True, default=None, null=True)),
                ('price_inr', models.IntegerField(blank=True, default=None, null=True)),
                ('price_usd', models.IntegerField(blank=True, default=None, null=True)),
                ('link_inr', models.SlugField(blank=True, default=None, null=True)),
                ('link_usd', models.SlugField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(blank=True, default=None, null=True)),
                ('intro', models.TextField(blank=True, default=None, null=True)),
                ('details', models.TextField(blank=True, default=None, null=True)),
                ('spl_details', models.TextField(blank=True, default=None, null=True)),
                ('link', models.SlugField(blank=True, default=None, null=True)),
                ('faicon', models.TextField(blank=True, default=None, null=True)),
                ('yt_link', models.TextField(blank=True, default=None, null=True)),
                ('is_available', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.TextField(blank=True, default=None, null=True)),
                ('customizations', models.TextField(blank=True, default=None, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('pending', models.BooleanField(blank=True, default=True, null=True)),
                ('payment_pending', models.TextField(blank=True, default=None, null=True)),
                ('total_amount', models.TextField(blank=True, default=None, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SopPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customizations', models.IntegerField(blank=True, default=None, null=True)),
                ('price_usd', models.IntegerField(blank=True, default=None, null=True)),
                ('price_inr', models.IntegerField(blank=True, default=None, null=True)),
                ('link_inr', models.SlugField(blank=True, default=None, null=True)),
                ('link_usd', models.SlugField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], default=1)),
                ('detail', models.TextField()),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(blank=True, default=None, null=True, upload_to='testimonials/')),
                ('rating', models.IntegerField(blank=True, default=None, null=True)),
                ('headline', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('details', models.TextField(blank=True, default=None, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('anonymous', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ToeflConsultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.TextField(blank=True, default=None, null=True)),
                ('price_inr', models.IntegerField(blank=True, default=None, null=True)),
                ('price_usd', models.IntegerField(blank=True, default=None, null=True)),
                ('link_inr', models.SlugField(blank=True, default=None, null=True)),
                ('link_usd', models.SlugField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnivShortlising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.TextField(blank=True, default=None, null=True)),
                ('price_inr', models.IntegerField(blank=True, default=None, null=True)),
                ('price_usd', models.IntegerField(blank=True, default=None, null=True)),
                ('link_inr', models.SlugField(blank=True, default=None, null=True)),
                ('link_usd', models.SlugField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='materialuser',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Payment'),
        ),
        migrations.AddField(
            model_name='materialuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
