# Generated by Django 2.1.5 on 2019-10-22 16:01

import account.storage
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', null=True)),
                ('email', models.TextField(blank=True, default=None, null=True)),
                ('subject', models.TextField(blank=True, default=None, null=True)),
                ('message', models.TextField(blank=True, default=None, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortname', models.CharField(max_length=5)),
                ('name', models.TextField()),
                ('phone_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Decisions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type', models.TextField(blank=True, default=None, null=True)),
                ('final', models.BooleanField(blank=True, default=False, null=True)),
                ('application_date', models.DateTimeField(default=datetime.datetime(2019, 10, 22, 16, 1, 58, 487438))),
                ('decision_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backlogs', models.IntegerField(blank=True, default=0, null=True)),
                ('area_of_study', models.TextField(blank=True, choices=[('Engineering', 'Engineering'), ('Business', 'Business'), ('Law', 'Law'), ('Medicine', 'Medicine')], default=None, null=True)),
                ('has_taken_gre', models.BooleanField(blank=True, default=False, null=True)),
                ('gmat', models.IntegerField(blank=True, default=None, null=True)),
                ('lsat', models.IntegerField(blank=True, default=None, null=True)),
                ('has_taken_toefl', models.BooleanField(blank=True, default=False, null=True)),
                ('cgpa', models.FloatField(blank=True, default=None, null=True)),
                ('cgpa_out_of', models.IntegerField(blank=True, default=None, null=True)),
                ('work_ex_months', models.IntegerField(blank=True, default=None, null=True)),
                ('research_papers', models.IntegerField(blank=True, default=None, null=True)),
                ('resume', models.FileField(blank=True, default=None, null=True, upload_to='resume/')),
                ('int_term', models.TextField(blank=True, default=None, null=True)),
                ('int_year', models.IntegerField(blank=True, default=2020, null=True)),
                ('achievements', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GREScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbal', models.IntegerField(blank=True, default=None, null=True)),
                ('quant', models.IntegerField(blank=True, default=None, null=True)),
                ('awa', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IELTSScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaking', models.FloatField(blank=True, default=None, null=True)),
                ('listening', models.FloatField(blank=True, default=None, null=True)),
                ('writing', models.FloatField(blank=True, default=None, null=True)),
                ('reading', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(blank=True, default=None, null=True)),
                ('duration_months', models.TextField(blank=True, default=None, null=True)),
                ('position', models.TextField(blank=True, default=None, null=True)),
                ('details', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LatestWhatsappGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='MCATScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(blank=True, default=None, null=True)),
                ('chemical_physical', models.IntegerField(blank=True, default=None, null=True)),
                ('critical_analysis', models.IntegerField(blank=True, default=None, null=True)),
                ('biologic_biochemical', models.IntegerField(blank=True, default=None, null=True)),
                ('psycho_social_biological', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtpDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=10)),
                ('mobile_otp', models.TextField(default=1, max_length=5)),
                ('verified', models.BooleanField(default=False)),
                ('confirm_mobile', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default=None, null=True)),
                ('website', models.TextField(blank=True, default=None, null=True)),
                ('details', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('referred_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrer', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SATScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(blank=True, default=None, null=True)),
                ('math', models.IntegerField(blank=True, default=None, null=True)),
                ('reading_writing', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(default='default_user.jpg', upload_to='profile_pics/')),
                ('mobile', models.BigIntegerField()),
                ('how_did_you_hear_about_us', models.TextField(choices=[('YouTube', 'YouTube'), ('Instagram', 'Instagram'), ('Google', 'Google'), ('Facebook', 'Facebook'), ('Referral', 'Referral'), ('Campus Ambassador', 'Campus Ambassador'), ('Other', 'Other')], default=1)),
                ('promo_msg_sent', models.BooleanField(default=False)),
                ('graduate', models.BooleanField(default=True)),
                ('dob', models.DateTimeField(blank=True, default=None, null=True)),
                ('complete_profile', models.BooleanField(default=False)),
                ('about', models.TextField(blank=True, default=None, null=True)),
                ('website', models.SlugField(blank=True, default=None, max_length=200, null=True)),
                ('plan_valid_till', models.DateTimeField(default=datetime.datetime(2019, 10, 22, 16, 1, 58, 468399))),
                ('no_of_questions_asked', models.IntegerField(default=0)),
                ('publisher', models.BooleanField(default=False)),
                ('study_material_page_opens', models.IntegerField(default=0)),
                ('study_material_email_threshold', models.IntegerField(default=3)),
                ('no_of_referrals', models.IntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Country')),
                ('payments', models.ManyToManyField(blank=True, null=True, related_name='payments', to='services.Payment')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.State')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TOEFLScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(blank=True, default=None, null=True)),
                ('speaking', models.IntegerField(blank=True, default=None, null=True)),
                ('listening', models.IntegerField(blank=True, default=None, null=True)),
                ('writing', models.IntegerField(blank=True, default=None, null=True)),
                ('reading', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UndergradProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_of_study', models.TextField(blank=True, choices=[('Engineering', 'Engineering'), ('Business', 'Business'), ('Law', 'Law'), ('Medicine', 'Medicine')], default=None, null=True)),
                ('lsat', models.IntegerField(blank=True, default=None, null=True)),
                ('cgpa', models.FloatField(blank=True, default=None, null=True)),
                ('cgpa_out_of', models.IntegerField(blank=True, default=None, null=True)),
                ('school_name', models.TextField(blank=True, default=None, null=True)),
                ('achievements', models.TextField(blank=True, default=None, null=True)),
                ('resume', models.FileField(blank=True, default=None, null=True, storage=account.storage.OverwriteStorage(), upload_to='resume/')),
                ('ielts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.IELTSScore')),
                ('internships', models.ManyToManyField(related_name='ug_internships', to='account.Internship')),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Project')),
                ('sat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.SATScore')),
                ('toefl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.TOEFLScore')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UndergradUniversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(blank=True, default=None, null=True)),
                ('duration_months', models.TextField(blank=True, default=None, null=True)),
                ('position', models.TextField(blank=True, default=None, null=True)),
                ('details', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='gradprofile',
            name='gre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.GREScore'),
        ),
        migrations.AddField(
            model_name='gradprofile',
            name='ielts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.IELTSScore'),
        ),
        migrations.AddField(
            model_name='gradprofile',
            name='internships',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='grad_internships', to='account.Internship'),
        ),
        migrations.AddField(
            model_name='gradprofile',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major', to='account.Major'),
        ),
        migrations.AddField(
            model_name='gradprofile',
            name='mcat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.MCATScore'),
        ),
        migrations.AddField(
            model_name='gradprofile',
            name='projects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Project'),
        ),
        migrations.AddField(
            model_name='gradprofile',
            name='target_major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_major', to='account.Major'),
        ),
        migrations.AddField(
            model_name='gradprofile',
            name='target_university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.University'),
        ),
        migrations.AddField(
            model_name='gradprofile',
            name='toefl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.TOEFLScore'),
        ),
        migrations.AddField(
            model_name='gradprofile',
            name='undergrad_uni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UndergradUniversity'),
        ),
        migrations.AddField(
            model_name='gradprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradprofile',
            name='work_exp',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='work', to='account.Work'),
        ),
        migrations.AddField(
            model_name='decisions',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Major'),
        ),
        migrations.AddField(
            model_name='decisions',
            name='university',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.University'),
        ),
        migrations.AddField(
            model_name='decisions',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
